name: '19'
timestamp: 1491759463
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1491497928
positions:
  booksArticles: 'Module Position'
  aside: Aside
  sidebar: Sidebar
  fixedside: 'Module Position'
  mymodule: 'Module Position'
sections:
  top: Top
  slideshow: Slideshow
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  blog: Blog
  bottom: Bottom
  clients: Clients
  above-footer: Above-footer
  fixedside: Fixedside
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  menu:
    menu-7083: Menu
  position:
    position-position-6745: 'Module Position'
    position-position-1903: Aside
    position-position-9993: Sidebar
    position-position-9360: 'Module Position'
    position-position-6712: 'Module Position'
  content:
    system-content-2479: 'Page Content'
  logo:
    logo-7047: 'Logo / Image'
  social:
    social-3014: Social
  sidemenu:
    sidemenu-4556: 'Side Menu'
  spacer:
    spacer-7552: Spacer
  custom:
    custom-2864: 'Custom HTML'
  copyright:
    copyright-8031: Copyright
  mobile-menu:
    mobile-menu-5796: Mobile-menu
inherit:
  default:
    top: top
    menu-7083: menu-1048
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    blog: blog
    aside: aside
    position-position-1903: position-position-4734
    mainbar: mainbar
    system-content-2479: system-content-1587
    sidebar: sidebar
    position-position-9993: position-position-3949
    bottom: bottom
    clients: clients
    above-footer: above-footer
    fixedside: fixedside
    logo-7047: logo-2325
    social-3014: social-4741
    position-position-9360: position-position-8858
    sidemenu-4556: sidemenu-4376
    position-position-6712: position-position-4914
    spacer-7552: spacer-2607
    custom-2864: custom-2810
    footer: footer
    copyright-8031: copyright-1736
    offcanvas: offcanvas
    mobile-menu-5796: mobile-menu-5697
