name: _offline
timestamp: 1491759057
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _offline
  timestamp: 1491497929
positions:
  aside: Aside
  sidebar: Sidebar
  fixedside: 'Module Position'
  mymodule: 'Module Position'
sections:
  top: Top
  slideshow: Slideshow
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  blog: Blog
  bottom: Bottom
  clients: Clients
  above-footer: Above-footer
  fixedside: Fixedside
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  menu:
    menu-4423: Menu
  position:
    position-position-8441: Aside
    position-position-7024: Sidebar
    position-position-6005: 'Module Position'
    position-position-3025: 'Module Position'
  content:
    system-content-5694: 'Page Content'
  logo:
    logo-7812: 'Logo / Image'
  social:
    social-6375: Social
  sidemenu:
    sidemenu-5368: 'Side Menu'
  spacer:
    spacer-3434: Spacer
  custom:
    custom-2665: 'Custom HTML'
  copyright:
    copyright-3226: Copyright
  mobile-menu:
    mobile-menu-3697: Mobile-menu
inherit:
  default:
    top: top
    slideshow: slideshow
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    blog: blog
    aside: aside
    mainbar: mainbar
    sidebar: sidebar
    bottom: bottom
    clients: clients
    above-footer: above-footer
    fixedside: fixedside
    footer: footer
    offcanvas: offcanvas
    menu-4423: menu-1048
    position-position-8441: position-position-4734
    system-content-5694: system-content-1587
    position-position-7024: position-position-3949
    logo-7812: logo-2325
    social-6375: social-4741
    position-position-6005: position-position-8858
    sidemenu-5368: sidemenu-4376
    position-position-3025: position-position-4914
    spacer-3434: spacer-2607
    custom-2665: custom-2810
    copyright-3226: copyright-1736
    mobile-menu-3697: mobile-menu-5697
