name: _error
timestamp: 1491759057
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1491497928
positions:
  aside: Aside
  sidebar: Sidebar
  fixedside: 'Module Position'
  mymodule: 'Module Position'
sections:
  top: Top
  slideshow: Slideshow
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  blog: Blog
  bottom: Bottom
  clients: Clients
  above-footer: Above-footer
  fixedside: Fixedside
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  menu:
    menu-1158: Menu
  position:
    position-position-3477: Aside
    position-position-5254: Sidebar
    position-position-3565: 'Module Position'
    position-position-3441: 'Module Position'
  content:
    system-content-6005: 'Page Content'
  logo:
    logo-7609: 'Logo / Image'
  social:
    social-4812: Social
  sidemenu:
    sidemenu-3744: 'Side Menu'
  spacer:
    spacer-9580: Spacer
  custom:
    custom-5066: 'Custom HTML'
  copyright:
    copyright-3100: Copyright
  mobile-menu:
    mobile-menu-1741: Mobile-menu
inherit:
  default:
    top: top
    slideshow: slideshow
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    blog: blog
    aside: aside
    mainbar: mainbar
    sidebar: sidebar
    bottom: bottom
    clients: clients
    above-footer: above-footer
    fixedside: fixedside
    footer: footer
    offcanvas: offcanvas
    menu-1158: menu-1048
    position-position-3477: position-position-4734
    system-content-6005: system-content-1587
    position-position-5254: position-position-3949
    logo-7609: logo-2325
    social-4812: social-4741
    position-position-3565: position-position-8858
    sidemenu-3744: sidemenu-4376
    position-position-3441: position-position-4914
    spacer-9580: spacer-2607
    custom-5066: custom-2810
    copyright-3100: copyright-1736
    mobile-menu-1741: mobile-menu-5697
