version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1491497928
layout:
  top: {  }
  /slideshow/:
    -
      - position-position-2679
  intro: {  }
  features: {  }
  utility: {  }
  above: {  }
  testimonials: {  }
  blog: {  }
  /container-main/:
    -
      -
        'aside 25': {  }
      -
        'mainbar 50': {  }
      -
        'sidebar 25': {  }
  bottom: {  }
  clients: {  }
  above-footer: {  }
  /fixedside/:
    -
      - logo-7047
    -
      - social-3014
    -
      - 'position-position-9360 50'
      - 'sidemenu-4556 50'
    -
      - position-position-6712
    -
      - spacer-7552
    -
      - custom-2864
  footer: {  }
  offcanvas: {  }
structure:
  top:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  slideshow:
    type: section
    attributes:
      boxed: ''
      class: ''
  intro:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  features:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  utility:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  above:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  testimonials:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  blog:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  aside:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
    block:
      fixed: '1'
  mainbar:
    type: section
    subtype: main
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  sidebar:
    type: section
    subtype: aside
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
    block:
      fixed: '1'
  container-main:
    attributes:
      boxed: ''
  bottom:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  clients:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  above-footer:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  fixedside:
    type: section
    attributes:
      boxed: '0'
      class: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
content:
  position-position-2679:
    title: 'Module Position'
    attributes:
      key: carousel
  logo-7047:
    title: 'Logo / Image'
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: logo-2325
  social-3014:
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: social-4741
  position-position-9360:
    title: 'Module Position'
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: position-position-8858
  sidemenu-4556:
    title: 'Side Menu'
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: sidemenu-4376
  position-position-6712:
    title: 'Module Position'
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: position-position-4914
  spacer-7552:
    attributes:
      enabled: 0
    block:
      class: space-with-border
  custom-2864:
    title: 'Custom HTML'
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: custom-2810
