ordering:
  profile: ''
  working-on-your-site:
    site-settings: ''
    template-settings: ''
  create-a-post: ''
  2012-01-04-15-46-42: ''
  change-password: ''
  log-out: ''
items:
  create-a-post:
    id: 104
  working-on-your-site:
    id: 109
  working-on-your-site/site-settings:
    id: 113
  working-on-your-site/template-settings:
    id: 114
  2012-01-04-15-46-42:
    id: 106
  change-password:
    id: 103
  log-out:
    id: 107
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
  profile:
    id: 134
